/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tlyc_Choose */

#ifndef _Included_tlyc_Choose
#define _Included_tlyc_Choose
#ifdef __cplusplus
extern "C" {
#endif
#undef tlyc_Choose_FOCUS_TRAVERSABLE_UNKNOWN
#define tlyc_Choose_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef tlyc_Choose_FOCUS_TRAVERSABLE_DEFAULT
#define tlyc_Choose_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef tlyc_Choose_FOCUS_TRAVERSABLE_SET
#define tlyc_Choose_FOCUS_TRAVERSABLE_SET 2L
#undef tlyc_Choose_TOP_ALIGNMENT
#define tlyc_Choose_TOP_ALIGNMENT 0.0f
#undef tlyc_Choose_CENTER_ALIGNMENT
#define tlyc_Choose_CENTER_ALIGNMENT 0.5f
#undef tlyc_Choose_BOTTOM_ALIGNMENT
#define tlyc_Choose_BOTTOM_ALIGNMENT 1.0f
#undef tlyc_Choose_LEFT_ALIGNMENT
#define tlyc_Choose_LEFT_ALIGNMENT 0.0f
#undef tlyc_Choose_RIGHT_ALIGNMENT
#define tlyc_Choose_RIGHT_ALIGNMENT 1.0f
#undef tlyc_Choose_serialVersionUID
#define tlyc_Choose_serialVersionUID -7644114512714619750LL
#undef tlyc_Choose_serialVersionUID
#define tlyc_Choose_serialVersionUID 4613797578919906343LL
#undef tlyc_Choose_INCLUDE_SELF
#define tlyc_Choose_INCLUDE_SELF 1L
#undef tlyc_Choose_SEARCH_HEAVYWEIGHTS
#define tlyc_Choose_SEARCH_HEAVYWEIGHTS 1L
#undef tlyc_Choose_OPENED
#define tlyc_Choose_OPENED 1L
#undef tlyc_Choose_serialVersionUID
#define tlyc_Choose_serialVersionUID 4497834738069338734LL
#undef tlyc_Choose_DEFAULT_CURSOR
#define tlyc_Choose_DEFAULT_CURSOR 0L
#undef tlyc_Choose_CROSSHAIR_CURSOR
#define tlyc_Choose_CROSSHAIR_CURSOR 1L
#undef tlyc_Choose_TEXT_CURSOR
#define tlyc_Choose_TEXT_CURSOR 2L
#undef tlyc_Choose_WAIT_CURSOR
#define tlyc_Choose_WAIT_CURSOR 3L
#undef tlyc_Choose_SW_RESIZE_CURSOR
#define tlyc_Choose_SW_RESIZE_CURSOR 4L
#undef tlyc_Choose_SE_RESIZE_CURSOR
#define tlyc_Choose_SE_RESIZE_CURSOR 5L
#undef tlyc_Choose_NW_RESIZE_CURSOR
#define tlyc_Choose_NW_RESIZE_CURSOR 6L
#undef tlyc_Choose_NE_RESIZE_CURSOR
#define tlyc_Choose_NE_RESIZE_CURSOR 7L
#undef tlyc_Choose_N_RESIZE_CURSOR
#define tlyc_Choose_N_RESIZE_CURSOR 8L
#undef tlyc_Choose_S_RESIZE_CURSOR
#define tlyc_Choose_S_RESIZE_CURSOR 9L
#undef tlyc_Choose_W_RESIZE_CURSOR
#define tlyc_Choose_W_RESIZE_CURSOR 10L
#undef tlyc_Choose_E_RESIZE_CURSOR
#define tlyc_Choose_E_RESIZE_CURSOR 11L
#undef tlyc_Choose_HAND_CURSOR
#define tlyc_Choose_HAND_CURSOR 12L
#undef tlyc_Choose_MOVE_CURSOR
#define tlyc_Choose_MOVE_CURSOR 13L
#undef tlyc_Choose_NORMAL
#define tlyc_Choose_NORMAL 0L
#undef tlyc_Choose_ICONIFIED
#define tlyc_Choose_ICONIFIED 1L
#undef tlyc_Choose_MAXIMIZED_HORIZ
#define tlyc_Choose_MAXIMIZED_HORIZ 2L
#undef tlyc_Choose_MAXIMIZED_VERT
#define tlyc_Choose_MAXIMIZED_VERT 4L
#undef tlyc_Choose_MAXIMIZED_BOTH
#define tlyc_Choose_MAXIMIZED_BOTH 6L
#undef tlyc_Choose_serialVersionUID
#define tlyc_Choose_serialVersionUID 2673458971256075116LL
#undef tlyc_Choose_EXIT_ON_CLOSE
#define tlyc_Choose_EXIT_ON_CLOSE 3L
/*
 * Class:     tlyc_Choose
 * Method:    hamminga
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tlyc_Choose_hamminga
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tlyc_Choose
 * Method:    hammingb
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tlyc_Choose_hammingb
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tlyc_Choose
 * Method:    hammingc
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tlyc_Choose_hammingc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tlyc_Choose
 * Method:    hammingd
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tlyc_Choose_hammingd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
