/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tlyc_Choose1 */

#ifndef _Included_tlyc_Choose1
#define _Included_tlyc_Choose1
#ifdef __cplusplus
extern "C" {
#endif
#undef tlyc_Choose1_FOCUS_TRAVERSABLE_UNKNOWN
#define tlyc_Choose1_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef tlyc_Choose1_FOCUS_TRAVERSABLE_DEFAULT
#define tlyc_Choose1_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef tlyc_Choose1_FOCUS_TRAVERSABLE_SET
#define tlyc_Choose1_FOCUS_TRAVERSABLE_SET 2L
#undef tlyc_Choose1_TOP_ALIGNMENT
#define tlyc_Choose1_TOP_ALIGNMENT 0.0f
#undef tlyc_Choose1_CENTER_ALIGNMENT
#define tlyc_Choose1_CENTER_ALIGNMENT 0.5f
#undef tlyc_Choose1_BOTTOM_ALIGNMENT
#define tlyc_Choose1_BOTTOM_ALIGNMENT 1.0f
#undef tlyc_Choose1_LEFT_ALIGNMENT
#define tlyc_Choose1_LEFT_ALIGNMENT 0.0f
#undef tlyc_Choose1_RIGHT_ALIGNMENT
#define tlyc_Choose1_RIGHT_ALIGNMENT 1.0f
#undef tlyc_Choose1_serialVersionUID
#define tlyc_Choose1_serialVersionUID -7644114512714619750LL
#undef tlyc_Choose1_serialVersionUID
#define tlyc_Choose1_serialVersionUID 4613797578919906343LL
#undef tlyc_Choose1_INCLUDE_SELF
#define tlyc_Choose1_INCLUDE_SELF 1L
#undef tlyc_Choose1_SEARCH_HEAVYWEIGHTS
#define tlyc_Choose1_SEARCH_HEAVYWEIGHTS 1L
#undef tlyc_Choose1_OPENED
#define tlyc_Choose1_OPENED 1L
#undef tlyc_Choose1_serialVersionUID
#define tlyc_Choose1_serialVersionUID 4497834738069338734LL
#undef tlyc_Choose1_DEFAULT_CURSOR
#define tlyc_Choose1_DEFAULT_CURSOR 0L
#undef tlyc_Choose1_CROSSHAIR_CURSOR
#define tlyc_Choose1_CROSSHAIR_CURSOR 1L
#undef tlyc_Choose1_TEXT_CURSOR
#define tlyc_Choose1_TEXT_CURSOR 2L
#undef tlyc_Choose1_WAIT_CURSOR
#define tlyc_Choose1_WAIT_CURSOR 3L
#undef tlyc_Choose1_SW_RESIZE_CURSOR
#define tlyc_Choose1_SW_RESIZE_CURSOR 4L
#undef tlyc_Choose1_SE_RESIZE_CURSOR
#define tlyc_Choose1_SE_RESIZE_CURSOR 5L
#undef tlyc_Choose1_NW_RESIZE_CURSOR
#define tlyc_Choose1_NW_RESIZE_CURSOR 6L
#undef tlyc_Choose1_NE_RESIZE_CURSOR
#define tlyc_Choose1_NE_RESIZE_CURSOR 7L
#undef tlyc_Choose1_N_RESIZE_CURSOR
#define tlyc_Choose1_N_RESIZE_CURSOR 8L
#undef tlyc_Choose1_S_RESIZE_CURSOR
#define tlyc_Choose1_S_RESIZE_CURSOR 9L
#undef tlyc_Choose1_W_RESIZE_CURSOR
#define tlyc_Choose1_W_RESIZE_CURSOR 10L
#undef tlyc_Choose1_E_RESIZE_CURSOR
#define tlyc_Choose1_E_RESIZE_CURSOR 11L
#undef tlyc_Choose1_HAND_CURSOR
#define tlyc_Choose1_HAND_CURSOR 12L
#undef tlyc_Choose1_MOVE_CURSOR
#define tlyc_Choose1_MOVE_CURSOR 13L
#undef tlyc_Choose1_NORMAL
#define tlyc_Choose1_NORMAL 0L
#undef tlyc_Choose1_ICONIFIED
#define tlyc_Choose1_ICONIFIED 1L
#undef tlyc_Choose1_MAXIMIZED_HORIZ
#define tlyc_Choose1_MAXIMIZED_HORIZ 2L
#undef tlyc_Choose1_MAXIMIZED_VERT
#define tlyc_Choose1_MAXIMIZED_VERT 4L
#undef tlyc_Choose1_MAXIMIZED_BOTH
#define tlyc_Choose1_MAXIMIZED_BOTH 6L
#undef tlyc_Choose1_serialVersionUID
#define tlyc_Choose1_serialVersionUID 2673458971256075116LL
#undef tlyc_Choose1_EXIT_ON_CLOSE
#define tlyc_Choose1_EXIT_ON_CLOSE 3L
/*
 * Class:     tlyc_Choose1
 * Method:    desprotegera
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tlyc_Choose1_desprotegera
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tlyc_Choose1
 * Method:    desprotegerb
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tlyc_Choose1_desprotegerb
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tlyc_Choose1
 * Method:    desprotegerc
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tlyc_Choose1_desprotegerc
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tlyc_Choose1
 * Method:    desprotegerd
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tlyc_Choose1_desprotegerd
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
