/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tlyc_ProteccionEncriptacion */

#ifndef _Included_tlyc_ProteccionEncriptacion
#define _Included_tlyc_ProteccionEncriptacion
#ifdef __cplusplus
extern "C" {
#endif
#undef tlyc_ProteccionEncriptacion_FOCUS_TRAVERSABLE_UNKNOWN
#define tlyc_ProteccionEncriptacion_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef tlyc_ProteccionEncriptacion_FOCUS_TRAVERSABLE_DEFAULT
#define tlyc_ProteccionEncriptacion_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef tlyc_ProteccionEncriptacion_FOCUS_TRAVERSABLE_SET
#define tlyc_ProteccionEncriptacion_FOCUS_TRAVERSABLE_SET 2L
#undef tlyc_ProteccionEncriptacion_TOP_ALIGNMENT
#define tlyc_ProteccionEncriptacion_TOP_ALIGNMENT 0.0f
#undef tlyc_ProteccionEncriptacion_CENTER_ALIGNMENT
#define tlyc_ProteccionEncriptacion_CENTER_ALIGNMENT 0.5f
#undef tlyc_ProteccionEncriptacion_BOTTOM_ALIGNMENT
#define tlyc_ProteccionEncriptacion_BOTTOM_ALIGNMENT 1.0f
#undef tlyc_ProteccionEncriptacion_LEFT_ALIGNMENT
#define tlyc_ProteccionEncriptacion_LEFT_ALIGNMENT 0.0f
#undef tlyc_ProteccionEncriptacion_RIGHT_ALIGNMENT
#define tlyc_ProteccionEncriptacion_RIGHT_ALIGNMENT 1.0f
#undef tlyc_ProteccionEncriptacion_serialVersionUID
#define tlyc_ProteccionEncriptacion_serialVersionUID -7644114512714619750LL
#undef tlyc_ProteccionEncriptacion_serialVersionUID
#define tlyc_ProteccionEncriptacion_serialVersionUID 4613797578919906343LL
#undef tlyc_ProteccionEncriptacion_INCLUDE_SELF
#define tlyc_ProteccionEncriptacion_INCLUDE_SELF 1L
#undef tlyc_ProteccionEncriptacion_SEARCH_HEAVYWEIGHTS
#define tlyc_ProteccionEncriptacion_SEARCH_HEAVYWEIGHTS 1L
#undef tlyc_ProteccionEncriptacion_OPENED
#define tlyc_ProteccionEncriptacion_OPENED 1L
#undef tlyc_ProteccionEncriptacion_serialVersionUID
#define tlyc_ProteccionEncriptacion_serialVersionUID 4497834738069338734LL
#undef tlyc_ProteccionEncriptacion_DEFAULT_CURSOR
#define tlyc_ProteccionEncriptacion_DEFAULT_CURSOR 0L
#undef tlyc_ProteccionEncriptacion_CROSSHAIR_CURSOR
#define tlyc_ProteccionEncriptacion_CROSSHAIR_CURSOR 1L
#undef tlyc_ProteccionEncriptacion_TEXT_CURSOR
#define tlyc_ProteccionEncriptacion_TEXT_CURSOR 2L
#undef tlyc_ProteccionEncriptacion_WAIT_CURSOR
#define tlyc_ProteccionEncriptacion_WAIT_CURSOR 3L
#undef tlyc_ProteccionEncriptacion_SW_RESIZE_CURSOR
#define tlyc_ProteccionEncriptacion_SW_RESIZE_CURSOR 4L
#undef tlyc_ProteccionEncriptacion_SE_RESIZE_CURSOR
#define tlyc_ProteccionEncriptacion_SE_RESIZE_CURSOR 5L
#undef tlyc_ProteccionEncriptacion_NW_RESIZE_CURSOR
#define tlyc_ProteccionEncriptacion_NW_RESIZE_CURSOR 6L
#undef tlyc_ProteccionEncriptacion_NE_RESIZE_CURSOR
#define tlyc_ProteccionEncriptacion_NE_RESIZE_CURSOR 7L
#undef tlyc_ProteccionEncriptacion_N_RESIZE_CURSOR
#define tlyc_ProteccionEncriptacion_N_RESIZE_CURSOR 8L
#undef tlyc_ProteccionEncriptacion_S_RESIZE_CURSOR
#define tlyc_ProteccionEncriptacion_S_RESIZE_CURSOR 9L
#undef tlyc_ProteccionEncriptacion_W_RESIZE_CURSOR
#define tlyc_ProteccionEncriptacion_W_RESIZE_CURSOR 10L
#undef tlyc_ProteccionEncriptacion_E_RESIZE_CURSOR
#define tlyc_ProteccionEncriptacion_E_RESIZE_CURSOR 11L
#undef tlyc_ProteccionEncriptacion_HAND_CURSOR
#define tlyc_ProteccionEncriptacion_HAND_CURSOR 12L
#undef tlyc_ProteccionEncriptacion_MOVE_CURSOR
#define tlyc_ProteccionEncriptacion_MOVE_CURSOR 13L
#undef tlyc_ProteccionEncriptacion_NORMAL
#define tlyc_ProteccionEncriptacion_NORMAL 0L
#undef tlyc_ProteccionEncriptacion_ICONIFIED
#define tlyc_ProteccionEncriptacion_ICONIFIED 1L
#undef tlyc_ProteccionEncriptacion_MAXIMIZED_HORIZ
#define tlyc_ProteccionEncriptacion_MAXIMIZED_HORIZ 2L
#undef tlyc_ProteccionEncriptacion_MAXIMIZED_VERT
#define tlyc_ProteccionEncriptacion_MAXIMIZED_VERT 4L
#undef tlyc_ProteccionEncriptacion_MAXIMIZED_BOTH
#define tlyc_ProteccionEncriptacion_MAXIMIZED_BOTH 6L
#undef tlyc_ProteccionEncriptacion_serialVersionUID
#define tlyc_ProteccionEncriptacion_serialVersionUID 2673458971256075116LL
#undef tlyc_ProteccionEncriptacion_EXIT_ON_CLOSE
#define tlyc_ProteccionEncriptacion_EXIT_ON_CLOSE 3L
/*
 * Class:     tlyc_ProteccionEncriptacion
 * Method:    desproteger
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tlyc_ProteccionEncriptacion_desproteger
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tlyc_ProteccionEncriptacion
 * Method:    comprimir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tlyc_ProteccionEncriptacion_comprimir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tlyc_ProteccionEncriptacion
 * Method:    descomprimir
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tlyc_ProteccionEncriptacion_descomprimir
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
